version: 2  # https://circleci.com/docs/2.0/adv-config/
jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            cd iaac/ && find . -type f -name '*.sh' -exec shellcheck --external-sources {} \; && cd -
  yamllint:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install YamlLint
          command: pip install --user yamllint
      - run:
          name: Run YamlLint
          command: |
            export PATH=/home/circleci/.local/bin:$PATH
            yamllint -d relaxed .
            find . -type f -name '*.yml' | wc -l
            find . -type f -name '*.yml' -exec yamllint {} \;
workflows:
  version: 2
  check-build:
    jobs:
      - shellcheck:
          filters:
            branches: # only run shellcheck on branchs
              only:
                - main
                - master
                - dev
      - yamllint:
          filters:
            branches: # only run shellcheck on branchs
              only:
                - main
                - master
                - dev
