---

- name: Pre-Tasks | Install required packages with apt
  apt:
    pkg:
      - git
      - python-virtualenv
      - libssl-dev
      - libffi-dev
      - build-essential
      - libpython3-dev
      - python3-minimal
      - authbind
      - virtualenv
      - apt-transport-https
      - sqlite3
    state: present
  when: ansible_os_family == 'Debian'



#sudo apt-get update && sudo apt-get install filebeat
#sudo systemctl enable filebeat

