---

- hosts: cowrie
  gather_facts: true
  serial: 1

  pre_tasks:
    - name: Distribution
      debug: msg="{{ ansible_os_family }} -> {{ ansible_distribution }} {{ ansible_distribution_version }}.{{ ansible_distribution_major_version }}"

  roles:
    - common_role
    - cowrie_role
