---

- name: Splunk | Copy splunk rpm
  copy:
    src: files/splunk-8.1.3-63079c59e632-linux-2.6-x86_64.rpm
    dest: /tmp/splunk.rpm

- name: Splunk | Install rpm splunk
  shell: rpm -i /tmp/splunk.rpm
  ignore_errors: true
  register: reboot_required_file

- name: Splunk | set permission directory splunk
  file:
    path: "{{ splunk_path }}"
    state: directory
    owner: splunk
    group: splunk
    mode: '0750'
  when: reboot_required_file.changed

#iptables -I INPUT 1 -p tcp --dport 8000 -j ACCEPT
- name: Splunk | Insert a rule port 8000 (Splunk interface) open in firewall
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 8000
    jump: ACCEPT
    action: insert
    rule_num: 1

- name: Splunk | Insert a rule port 5044 (logstash) open in firewall
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 5044
    jump: ACCEPT
    action: insert
    rule_num: 2

# This will apply to all loaded/active IPv4 tables.
# ansible-galaxy collection install community.general
- name: Splunk | Save current state of the firewall in system file
  community.general.iptables_state:
    state: saved
    path: /etc/sysconfig/iptables

- name: Copy config user admin splunk
  copy:
    src: files/user.conf
    dest: "{{ splunk_path }}/etc/system/local/user-seed.conf"
    owner: splunk
    group: splunk
  when: reboot_required_file.changed

- name: Splunk | Accept license
  shell: "{{ splunk_path }}/bin/splunk start --accept-license --answer-yes --no-prompt"
  become: yes
  become_method: su
  become_user: splunk
  when: reboot_required_file.changed


- name: Splunk | Create a directory certificates
  file:
    path: "{{ splunk_path_ssl }}"
    state: directory
    owner: splunk
    group: splunk
    mode: '0700'

- name: Splunk | Copy certificates
  copy:
    src: "{{ item }}"
    dest: "{{ splunk_path_ssl }}"
    owner: splunk
    group: splunk
    mode: '0600'
  with_items:
    - files/ssl/splunk.key
    - files/ssl/splunk.crt

- name: Splunk | Enable SSL in HTTPS
  lineinfile:
    path: "{{ splunk_path }}/etc/system/default/web.conf"
    regexp: '^enableSplunkWebSSL\s*=\s*false$'
    line: "enableSplunkWebSSL = true"
  notify: Restart service Splunk

- name: Splunk | Set path private keyt ssl
  lineinfile:
    path: "{{ splunk_path }}/etc/system/default/web.conf"
    regexp: '^#?\s*privKeyPath\s*=.*$'
    line: "privKeyPath = {{ splunk_path_ssl }}/splunk.key"
  notify: Restart service Splunk

- name: Splunk | Set path public keyt ssl
  lineinfile:
    path: "{{ splunk_path }}/etc/system/default/web.conf"
    regexp: '^#?\s*serverCert\s*=.*$'
    line: "serverCert = {{ splunk_path_ssl }}/splunk.crt"
  notify: Restart service Splunk

- name: "Splunk | Set web port in {{ splunk_web_port }}"
  lineinfile:
    path: "{{ splunk_path }}/etc/system/default/web.conf"
    regexp: '^#?\s*httpport\s*=.*$'
    line: "httpport = {{ splunk_web_port }}"
  notify: Restart service Splunk

- name: Splunk | Enable service splunk
  shell: "{{ splunk_path }}/bin/splunk enable boot-start -user splunk"
  when: reboot_required_file.changed

- block:
  - name: Splunk | Force execute handler restart services
    meta: flush_handlers

  - name: Splunk | Is active service
    shell: systemctl is-active splunk
    register: result
    failed_when:
      - result.rc != 0

- name: Splunk | Reboot the box if kernel updated
  reboot:
    msg: "Reboot initiated by Ansible for apply config splunk"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.changed


- name: Splunk | Validating web port is open
  wait_for:
    host: "{{ ansible_ssh_host }}"
    port: "{{ splunk_web_port }}"
    delay: 10
    timeout: 30
    state: started
    msg: "splunk web is not running"
  ignore_errors: true
  when: reboot_required_file.changed


- name: Splunk | set permission directory audit
  file:
    path: /var/log/audit/
    state: directory
    owner: root
    group: splunk
    mode: '0750'
    recurse: yes

- name: Splunk | set permission directory audit
  file:
    path: /var/log/audit/audit.log
    state: file
    owner: root
    group: splunk
    mode: '0740'




