---
# defaults file for cowrie_role

cowrie_user: cowrie
cowrie_path: "/home/{{ cowrie_user }}/{{ cowrie_user }}"
cowrie_venv: "/home/{{ cowrie_user }}/cowrie-env"


# [ssh]
ssh_enable: "true"

# [telnet]
telnet_enabled: "false"

# [output_virustotal]
vt_enable: "false"

# [output_splunk]
splunk_enable: "true"
splunk_url: https://localhost:8088/services/collector/event
splunk_index: cowrie
splunk_sourcetype: cowrie
splunk_source: cowrie

# [output_sqlite]
db_enable: "false"

# [output_jsonlog]
json_enable: "true"

