---
- hosts: nginx
  gather_facts: true
  serial: 1

  pre_tasks:
    - name: Distribution
      debug: msg="{{ ansible_os_family }} -> {{ ansible_distribution }} {{ ansible_distribution_version }}.{{ ansible_distribution_major_version }}"

    - name: Inlcude vars all servers
      include_vars:
        file: var_servers.yml

  roles:
    - common_role
    - nginx_role

