---

- hosts: splunk
  gather_facts: true
  serial: 1

  pre_tasks:
    - name: Distribution
      debug: msg="{{ ansible_os_family }} -> {{ ansible_distribution }} {{ ansible_distribution_version }}.{{ ansible_distribution_major_version }}"

  roles:
    - common_role
    - splunk_role


# curl -k "http://192.168.1.14:8088/services/collector/event" \
# -H "Authorization: Splunk d785742f-c9a1-490a-b508-357c21306c3d" \
# -d '{"event": "Hello world"}'