---
# defaults file for tig_role

group_tig: tig
tig_path_ssl: "/etc/ssl"
#tig_path_ssl: "/etc/ssl/{{ group_tig }}"

# [server]

grafana_cert_file: "{{ tig_path_ssl }}/grafana.crt"
grafana_cert_key: "{{ tig_path_ssl }}/grafana.key"
grafana_domain: "{{ endpoints['grafana'].name }}"
grafana_enforce_domain: "false"
# [auth.anonymous]
grafana_org_name: "{{ domain }} S.L."

# [http]
influx_auth_enabled: "false"  # para que se requieras autenticacion en las queries
influx_https_enabled: "true"
influx_path_ssl: /etc/influxdb/ssl
influx_https_certificate: "{{ tig_path_ssl }}/influx.pem"
influx_https_private_key: "{{ tig_path_ssl }}/influx.key"

telegraf_hostname: tig
telegraf_https_ca: "{{ tig_path_ssl }}/ca.pem"
telegraf_https_certificate: "{{ tig_path_ssl }}/telegraf.pem"
telegraf_https_private_key: "{{ tig_path_ssl }}/telegraf.key"