---

# ERROR: Cannot open TUN/TAP dev /dev/net/tun:
#https://blog.guillen.io/2016/08/22/lxc-openvz-openvpn-tun-tap-error/

# Paso 1: Instalar OpenVPN y Easy-RSA
- block:
  - name: OpenVPN | Create dir easy_rsa
    file:
      path: "{{ path_easy_rsa }}"
      state: directory
      owner: root
      group: root

  - name: OpenVPN | Create link easy_rsa
    shell: ln -s /usr/share/easy-rsa/3/* "{{ path_easy_rsa }}"
    ignore_errors: true
    no_log: true

  #- name: OpenVPN | Create link easy_rsa
  #  file:
  ##    path: "{{ path_easy_rsa }}"
  ##    state: directory
  #    src: /usr/share/easy-rsa/3/
  #    dest: "{{ path_easy_rsa }}/"
  #    state: link
  #    force: yes

# Paso 2: Crear una PKI para OpenVPN
- block:
  - name: OpenVPN | Create vars PKI
    template:
      src: vars.j2
      dest: "{{ path_easy_rsa }}/vars"
      mode: 0644
      owner: root
      group: root

  - name: "OpenVPN | Remove {{ path_easy_rsa }}/pki if exists"
    file:
      path: "{{ path_easy_rsa }}/pki"
      state: absent

  - name: OpenVPN | Create PKI
    shell: "{{ path_easy_rsa }}/easyrsa init-pki"
    args:
      chdir: "{{ path_easy_rsa }}"

  - name: OpenVPN | Create CA
    shell: "{{ path_easy_rsa }}/easyrsa --batch build-ca nopass"
    args:
      chdir: "{{ path_easy_rsa }}"

# Paso 3: Crear una solicitud de certificado de servidor de OpenVPN y una clave privada
- block:
  - name: OpenVPN | gen-req {{ vpn_cn }}
    shell: "{{ path_easy_rsa }}/easyrsa --batch gen-req {{ vpn_cn }} nopass"
    args:
      chdir: "{{ path_easy_rsa }}"


# Paso 4: Firmar la solicitud de certificado del servidor de OpenVPN
- name: OpenVPN | sign-req {{ vpn_cn }}
  shell: "{{ path_easy_rsa }}/easyrsa --batch sign-req server {{ vpn_cn }}"
  args:
    chdir: "{{ path_easy_rsa }}"

# Paso 5: Configurar materiales de cifrado de OpenVPN
- block:
  - name: OpenVPN | Generate key tls-crypt
    shell: "openvpn --genkey --secret {{ key_tls }}"
    args:
      chdir: "{{ path_easy_rsa }}"



# Paso 6: Generar un par de certificado y clave de cliente
- block:

  - name: OpenVPN | Create dir client
    file:
      path: "{{ path_clients }}"
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: OpenVPN | Create dir client certificates
    file:
      path: "{{ path_clients_ssl }}"
      state: directory
      owner: root
      group: root
      mode: 0700

  - name: OpenVPN | Generate clients certificates
    shell: "{{ path_easy_rsa }}/easyrsa --batch gen-req {{ item }} nopass"
    args:
      chdir: "{{ path_easy_rsa }}"
    with_items:
      - "{{ test_client }}"

  - name: OpenVPN | sign-req clients
    shell: "{{ path_easy_rsa }}/easyrsa --batch sign-req client {{ item }}"
    args:
      chdir: "{{ path_easy_rsa }}"
    with_items:
      - "{{ test_client }}"

- block:
  - name: OpenVPN | Copy key tls-crypt
    copy:
      src: "{{ path_easy_rsa }}/{{ key_tls }}"
      dest: "{{ path_ssl }}"
      remote_src: true
      owner: root
      group: root
      mode: 0600

  - name: OpenVPN | Copy certificates
    copy:
      src: "{{ path_easy_rsa }}/pki/{{ item.path }}/{{ item.file }}"
      dest: "{{ item.dest }}"
      remote_src: true
      owner: root
      group: root
      mode: 0600
    with_items:
      - { path: private, file: ca.key, dest: "{{ path_ssl }}"}
      - { path: ., file: ca.crt, dest: "{{ path_ssl }}"}
      - { path: private, file: "{{ vpn_cn }}.key", dest: "{{ path_ssl }}"}
      - { path: issued, file: "{{ vpn_cn }}.crt", dest: "{{ path_ssl }}"}
      - { path: private, file: "{{ test_client }}.key", dest: "{{ path_clients_ssl }}"}
      - { path: issued, file: "{{ test_client }}.crt", dest: "{{ path_clients_ssl }}"}

# Paso 7: Configurar OpenVPN
- name: OpenVPN | Create vars PKI
  template:
    src: server.conf
    dest: /etc/openvpn/server/server.conf
    mode: 0666
    owner: root
    group: root

# Paso 8: Ajustar la configuración de redes del servidor de OpenVPN
- name: OpenVPN | Forward IPv4
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes

# Paso 9: Configuración del firewall
# sudo firewall-cmd --permanent --direct --passthrough ipv4 -t nat -A POSTROUTING -s 172.16.0.0/24 -o eth0 -j MASQUERADE
# sudo iptables -t nat -A POSTROUTING -s 172.16.0.0/24 -o eth0 -j MASQUERADE
#- name: OpenVPN | Postrouting vpn network
#  iptables:
#    table: nat
#    chain: POSTROUTING
#    source: "{{ vpn_net }}/{{ vpn_mask }}"
#    out_interface: eth0
#    jump: MASQUERADE
#
#    #protocol: tcp
#    #match: tcp
##    destination_port: 80
##    to_ports: 8600
#    comment: Redirect web traffic to port 8600
#  become: yes

# Paso 10: Iniciar OpenVPN
- name: Enable and Start service OpenVPN
  systemd:
    name: openvpn-server@server.service
    state: restarted
    daemon_reload: yes
    enabled: yes

# Paso 11: Crear la infraestructura de configuración de clientes
- block:
  - name: OpenVPN | Create dir client files
    file:
      path: "{{ path_clients }}/files"
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: OpenVPN | Copy config clients
    template:
      src: clients.conf
      dest: "{{ path_clients }}/clients.conf"
      mode: 0644
      owner: root
      group: root

  - name: OpenVPN | Copy script generate clients
    template:
      src: openvpn_add.sh
      dest: /usr/local/bin/
      mode: 0755

  - name: OpenVPN | Generate config client
    shell: "openvpn_add.sh {{ test_client }}"




